import os
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (Conv2D,MaxPooling2D,Dense,Dropout,GlobalAveragePooling2D)

# Path to the dataset generated by ds_generator
dataset_dir = os.path.join("..", "ds_generator", "dataset")

# Create dataloaders
batch_size = 32
img_height = 256
img_width = 256

# Use image_dataset_from_directory to load the dataset
# This assumes the dataset folder has subfolders for each class (e.g., 'cover', 'stego')
train_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    dataset_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=(img_height, img_width),
    batch_size=batch_size
)

# Normalize pixel values
normalization_layer = tf.keras.layers.Rescaling(1./255)
train_ds = train_ds.map(lambda x, y: (normalization_layer(x), y))
val_ds = val_ds.map(lambda x, y: (normalization_layer(x), y))

# Prefetch for performance
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

model = Sequential(
    [
        Conv2D(32,(3,3),activation="relu",padding="same",input_shape=(img_height,img_width,3)),
        MaxPooling2D((2,2)),
        Conv2D(64,(3,3),activation="relu",padding="same"),
        MaxPooling2D((2,2)),
        GlobalAveragePooling2D(),
        Dense(32,activation="relu"),
        Dropout(0.5),
        Dense(1,activation="sigmoid")
     ]
)
model.compile(
    optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"]
)

history=model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)